//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthWorksApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> ReferredBy { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public string DiagnosisDetails { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
